### PR TITLE
Fixed obsolete usleep call found by flawfinder (issue #9)

### PR DESCRIPTION
**Pull request by dandexter**

### CODE REVIEW

**Comment by ezcrues** [comment]
The "usleep" call is prototyped in unistd.h.  It looks like this is no longer needed in some of the *.cpp files.  Have you check to see if unistd.h can be removed?

**Comment by dandexter** [comment]
Good catch, I'll go take a look at the the unistd.h includes.

**Comment by dandexter** [comment]
I removed all the <unistd.h> system includes now that we don't use usleep().

**Comment by ezcrues** [comment]
Looks good.  I'll merge it into master.

**Pull request closed without merging**
